[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxfixes",
  "libxrandr",
  "libgbm",
  "alsa-lib",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libxcb",
  "libglvnd",
  "mesa",
  "fontconfig",
  "freetype",
  "chromium"
]
