[phases.setup]
nixPkgs = [
    "chromium",
    "libGL",
    "libglib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "libXcomposite",
    "libXdamage",
    "libXfixes",
    "libXrandr",
    "libgbm",
    "alsa-lib",
    "pango",
    "cairo"
]
