name: SHANA ai

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Latest Chrome (For Puppeteer)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Dependencies
        run: |
          npm install

      - name: Start SHANA AI Bot and Show QR
        run: |
          node index.js &
          echo "⏳ බොට් ක්‍රියාත්මක වෙමින් පවතී... තත්පර 20කින් QR කේතය දිස්වනු ඇත..."
          echo "⚠️ QR එක ස්කෑන් කිරීමට ඔබට විනාඩි 5ක කාලයක් ලැබේ!"
          sleep 300
          echo "✅ ක්‍රියාවලිය අවසන් විය."
